config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  get 'welcome/index'

  resources :categoria
  resources :ciudads
  resources :oferta

  root 'welcome#index'

  resources :usuario_sessions
  match 'login' => 'usuario_sessions#new', :via => [:get, :post], :as => 'usuario_sessions_new'
  match 'logout' => 'usuario_sessions#destroy', :via => [:get, :post], :as => 'usuario_sessions_destroy'

end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
	has_many :usuarios

	belongs_to :usuarios

	attr_accessible :ciudad
end

app/controllers/ciudads_controller.rb
class CiudadsController < ApplicationController
  before_action :set_ciudad, only: [:show, :edit, :update, :destroy]

  # GET /ciudads
  # GET /ciudads.json
  def index
    @ciudads = Ciudad.all
    #@rol = Usuario.find(current_user.rol)
    
  end

  def rol
    
  end

  # GET /ciudads/1
  # GET /ciudads/1.json
  def show
  end

  # GET /ciudads/new
  def new
    @ciudad = Ciudad.new
    #@rol = Usuario.find(current_user.rol)
  end

  # GET /ciudads/1/edit
  def edit
  end

  # POST /ciudads
  # POST /ciudads.json
  def create
    @ciudad = Ciudad.new(ciudad_params)

    respond_to do |format|
      if @ciudad.save
        format.html { redirect_to @ciudad, notice: 'Ciudad was successfully created.' }
        format.json { render :show, status: :created, location: @ciudad }
      else
        format.html { render :new }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ciudads/1
  # PATCH/PUT /ciudads/1.json
  def update
    respond_to do |format|
      if @ciudad.update(ciudad_params)
        format.html { redirect_to @ciudad, notice: 'Ciudad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ciudad }
      else
        format.html { render :edit }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ciudads/1
  # DELETE /ciudads/1.json
  def destroy
    @ciudad.destroy
    respond_to do |format|
      format.html { redirect_to ciudads_url, notice: 'Ciudad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ciudad
      @ciudad = Ciudad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ciudad_params
      params.require(:ciudad).permit(:ciudad)
    end
end

app/helpers/ciudads_helper.rb
module CiudadsHelper
end

app/views/ciudads/_form.html.erb
<h1>Nueva Ciudad</h1>

<%= form_for(@ciudad) do |f| %>
  <% if @ciudad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ciudad.errors.count, "error") %> prohibited this ciudad from being saved:</h2>
      <ul>
      <% @ciudad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.rol == 1 %>
  
  <div class="field">
    <%= f.label :ciudad %><br>
    <%= f.text_field :ciudad, class: "form-control" %>
  </div>
  <div class="boton-New-ofert">
  <div class="actions">
    <%= f.submit "Listo!", class: "btn btn-success" %>
  </div>
  </div>
  <% else %>
        <p>Debes iniciar sesión <%=link_to 'Login', usuario_sessions_new_path %></p>
<% end %> 
<% end %>

app/views/ciudads/edit.html.erb
<div class= "new-ofert">
<h1></h1>

<%= render 'form' %>
<div class="boton-New-ofert">
<%= link_to 'Vista Previa', @ciudad, class: "btn btn-primary" %> 
<%= link_to 'Volver', ciudads_path, class: "btn btn-danger" %>
</div>

</div>

app/views/ciudads/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.rol == 1 %>

<div class="contenedor-tabla">
<div class="table-responsive">
<h1>Ciudades</h1>

<table class="table table-condensed">
  <thead>
    <tr class="info">
      <th>Ciudad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ciudads.each do |ciudad| %>
      <tr class="active">
        <td><%= ciudad.ciudad %></td>
        <td><%= link_to 'Mostrar', ciudad, class: "btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_ciudad_path(ciudad), class: "btn btn-warning" %></td>
        <td><%= link_to 'Borrar', ciudad, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Ciudad', new_ciudad_path, class: "btn btn-success" %>

<% else %>
        <p>Debes iniciar sesión <%=link_to 'Login', usuario_sessions_new_path %></p>
<% end %> 

</div>
</div>

app/views/ciudads/new.html.erb
<div class= "new-ofert">

<%= render 'form' %>

<div class="boton-New-ofert">
<%= link_to 'Volver', ciudads_path, class: "btn btn-danger" %>
</div>
</div>

app/views/ciudads/show.html.erb
<% if current_user.rol==1 %>

<p id="notice"><%= notice %></p>
<div class="show">
<p class= "bg-primary">
  <strong>Ciudad:</strong>
  <%= @ciudad.ciudad %>
</p>

<%= link_to 'Editar', edit_ciudad_path(@ciudad), class: "btn btn-warning" %> 
<%= link_to 'Volver', ciudads_path, class: "btn btn-success" %>
</div>
<% else %>
        <p>Debes iniciar sesion <%=link_to 'Login', usuario_sessions_new_path %></p>
<% end %> 