config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  get 'welcome/index'

  resources :categoria
  resources :ciudads
  resources :oferta

  root 'welcome#index'

  resources :usuario_sessions
  match 'login' => 'usuario_sessions#new', :via => [:get, :post], :as => 'usuario_sessions_new'
  match 'logout' => 'usuario_sessions#destroy', :via => [:get, :post], :as => 'usuario_sessions_destroy'

end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: [:show, :edit, :update, :destroy]

  # GET /categoria
  # GET /categoria.json
  def index
    @categoria = Categorium.all
  end

  def rol
    
  end


  # GET /categoria/1
  # GET /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categorium = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria
  # POST /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: 'Categorium was successfully created.' }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1
  # PATCH/PUT /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to @categorium, notice: 'Categorium was successfully updated.' }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1
  # DELETE /categoria/1.json
  def destroy
    @categorium.destroy
    respond_to do |format|
      format.html { redirect_to categoria_url, notice: 'Categorium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categorium_params
      params.require(:categorium).permit(:categoria)
    end
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/views/categoria/_form.html.erb
<h1>Nueva Categoria</h1>

<%= form_for(@categorium) do |f| %>

  <% if @categorium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorium.errors.count, "error") %> prohibited this categorium from being saved:</h2>

      <ul>
      <% @categorium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.rol == 1 %>
  
  <div class="field">
    <%= f.label :categoria %><br>
    <%= f.text_field :categoria, class: "form-control" %>
  </div>
  <div class="boton-New-ofert">
  <div class="actions">
    <%= f.submit "Listo!", class: "btn btn-success" %>
  </div>
  </div>

  <% else %>
        <p>Debes iniciar sesión <%=link_to 'Login', usuario_sessions_new_path %></p>
  <% end %> 


<% end %>

app/views/categoria/edit.html.erb
<div class= "new-ofert">
<h1></h1>

<%= render 'form' %>
<div class="boton-New-ofert">
<%= link_to 'Vista Previa', @categorium, class: "btn btn-primary" %> 
<%= link_to 'Volver', categoria_path, class: "btn btn-danger" %>
</div>

</div>

app/views/categoria/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.rol == 1 %>

<div class="contenedor-tabla">
<div class="table-responsive">
<h1>Listing Categoria</h1>

<table class="table table-condensed">
  <thead>
    <tr class="info">
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria.each do |categorium| %>
      <tr class="active">
        <td><%= categorium.categoria %></td>
        <td><%= link_to 'Mostrar', categorium, class: "btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_categorium_path(categorium), class: "btn btn-warning" %></td>
        <td><%= link_to 'Borrar', categorium, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Categoria', new_categorium_path, class: "btn btn-success" %>

<% else %>
        <p>Debes iniciar sesión <%=link_to 'Login', usuario_sessions_new_path %></p>
<% end %> 

app/views/categoria/new.html.erb
<div class= "new-ofert">


<%= render 'form' %>

<div class="boton-New-ofert">
<%= link_to 'Volver', categoria_path, class: "btn btn-danger"  %>
</div>
</div>

app/views/categoria/show.html.erb
<% if current_user.rol==1 %>

<p id="notice"><%= notice %></p>
<div class="show">
<p class= "bg-primary">
  <strong>Categoria:</strong>
  <%= @categorium.categoria %>
</p>

<%= link_to 'Editar', edit_categorium_path(@categorium), class: "btn btn-warning" %> 
<%= link_to 'Volver', categoria_path, class: "btn btn-success"%>
</div>
<% else %>
        <p>Debes iniciar sesion <%=link_to 'Login', usuario_sessions_new_path %></p>
<% end %> 