config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  get 'welcome/index'

  resources :categoria
  resources :ciudads
  resources :oferta

  root 'welcome#index'

  resources :usuario_sessions
  match 'login' => 'usuario_sessions#new', :via => [:get, :post], :as => 'usuario_sessions_new'
  match 'logout' => 'usuario_sessions#destroy', :via => [:get, :post], :as => 'usuario_sessions_destroy'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base

	belongs_to :ciudads
	
	attr_accessible :email, :crypted_password, :salt, :password, :id, :rol, :ciudad_id
	authenticates_with_sorcery!
	validates_confirmation_of :password, message: "Ambos campos deben coincidir", if: :password_confirmation

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  def rol
    
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
    #@rol = Usuario.find(current_user.rol)

     
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:email, :rol, :crypted_password, :salt, :password, :ciudad_id)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<h1>Nuevo Usuario</h1>
<%= form_for(@usuario) do |f| %>

  <% if @usuario.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.rol == 1 %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :rol %><br>
    <%= f.number_field :rol, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :ciudad_id %><br>
    <%= f.collection_select :ciudad_id, Ciudad.all, :id, :ciudad, prompt: true, class: "form-control"  %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="boton-New-ofert">
  <div class="actions">
    <%= f.submit "Listo!", class: "btn btn-success"  %>
  </div>
  </div>

  <% else %>
        <p>Debes iniciar sesión <%=link_to 'Login', usuario_sessions_new_path %></p>
  <% end %> 

<% end %>

app/views/usuarios/edit.html.erb
<div class= "new-ofert">
<h1></h1>

<%= render 'form' %>
<div class="boton-New-ofert">
<%= link_to 'Vista Previa', @usuario, class: "btn btn-primary" %> 
<%= link_to 'Volver', usuarios_path, class: "btn btn-danger" %>
</div>

</div>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.rol == 1 %>

<div class="contenedor-tabla">
<div class="table-responsive">
<h1>Usuarios</h1>

<table class="table table-condensed">
  <thead>
   <tr class="info">
      <th>Email</th>
      <th>Ciudad</th>
      <th>Rol</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr class="active">
        <td><%= usuario.email %></td>
        <td><%= usuario.ciudad_id %></td>
        <td><%= usuario.rol %></td>
        
        <td><%= link_to 'Mosrar', usuario, class: "btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_usuario_path(usuario), class: "btn btn-warning" %></td>
        <td><%= link_to 'Borrar', usuario, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_usuario_path, class: "btn btn-success" %>

<% else %>
        <p>Debes iniciar sesión <%=link_to 'Login', usuario_sessions_new_path %></p>
<% end %> 

</div>
</div>

app/views/usuarios/new.html.erb
<div class= "new-ofert">
	
<h1></h1>
<p>1=admin, 3=premium, vacio ó 0=regular</p>
<%= render 'form' %>


<div class="boton-New-ofert">
<%= link_to 'Cancelar', usuarios_path, class: "btn btn-danger" %>
</div>
</div>

app/views/usuarios/show.html.erb
<% if current_user.rol==1 %>

<p id="notice"><%= notice %></p>

<div class="show">
<p class= "bg-primary">
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>
<p class= "bg-primary">
  <strong>Ciudad:</strong>
  <%= @usuario.ciudad_id %>
</p>
<p class= "bg-primary">
  <strong>Rol:</strong>
  <%= @usuario.rol %>
</p>



<%= link_to 'Editar', edit_usuario_path(@usuario), class: "btn btn-warning" %> 
<%= link_to 'Volver', usuarios_path, class: "btn btn-success" %>

</div>
<% else %>
        <p>Debes iniciar sesion <%=link_to 'Login', usuario_sessions_new_path %></p>
<% end %> 